# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: LaTeX compilation
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: model-based-management.tex
          # The working directory for the latex compiler to be invoked
          working_directory: publication

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.0
        with:
          # Artifact name
          name: publication_pdf
          # A file, directory or wildcard pattern that describes what to upload
          path: publication/model-based-management.pdf
          # The desired behavior if no files are found using the provided path.
 
